server:
  port: 80   #设置端口号为80
spring:
  datasource:
    url: jdbc:mysql://master.hadoop.nuist:33060/ehr?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mappers/*.xml